// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQAmObPXalwQdOYkrW8Ep2innh07Wv0vw',
    appId: '1:1071299133185:web:3e443a87ade42a24c36500',
    messagingSenderId: '1071299133185',
    projectId: 'screen-limit-8e771',
    authDomain: 'screen-limit-8e771.firebaseapp.com',
    databaseURL: 'https://screen-limit-8e771-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'screen-limit-8e771.appspot.com',
    measurementId: 'G-X2S6FZE0RT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABfBFvltNXd0LMHjG_3gG7PT5DA2tDCeI',
    appId: '1:1071299133185:android:c98aa5170f5db3efc36500',
    messagingSenderId: '1071299133185',
    projectId: 'screen-limit-8e771',
    databaseURL: 'https://screen-limit-8e771-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'screen-limit-8e771.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRHMMM_MMlYGF2aA8rq5i-VAEgR8GJ5io',
    appId: '1:1071299133185:ios:ecbe23bf00a9becac36500',
    messagingSenderId: '1071299133185',
    projectId: 'screen-limit-8e771',
    databaseURL: 'https://screen-limit-8e771-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'screen-limit-8e771.appspot.com',
    iosClientId: '1071299133185-8odc17i5ulohvggn0ffvlddbressuupt.apps.googleusercontent.com',
    iosBundleId: 'fr.dachet.screenlimit',
  );
}
